spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/projectg2
    username: root
    password: green502

mybatis:
  mapper-locations: mapper/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082
